name: Build

on:
  push:
  
jobs:
  osx-build:
    name: Build OSX Asset
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./run.sh
      
      - name: Package Files for upload
        run: zip -r sweeper-osx.zip dist

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: crown-osx.zip
          
  linux-build:
    name: Build Linux Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./run.sh
      
      - name: Package Files for upload
        run: zip -r sweeper-linux.zip dist

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: crown-osx.zip
          
  windows-build:
    name: Build Windows Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./run.sh
      
      - name: Package Files for upload
        run: zip -r sweeper-windows.zip dist

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: crown-osx.zip
          
