name: Build

on: [push]
  
jobs:
  linux-build:
    name: Build Linux Asset
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Build
        run: ./run.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sweeper-linux
          path: dist/CrownSweeper
