name: Build

on: [push]
  
jobs:
  linux-build:
    name: Build Linux Asset
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          apt-cache policy fontconfig 
          python -m pip install --upgrade pip

      - name: Build
        run: ./run.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sweeper-linux
          path: |
            dist/CrownSweeper
            CrownSweeper.spec


  osx-build:
    name: Build OSX Asset
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./run.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sweeper-osx
          path: |
            dist/CrownSweeper
            CrownSweeper.spec
          
          
  windows-build:
    name: Build Windows Asset
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./run.sh
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sweeper-windows
          path: |
            dist/CrownSweepersweeper-windows.zip
            CrownSweeper.spec
